"""
vkflow.commands
~~~~~~~~~~~~~~~~

Command framework: decorators, Cog, Context, checks, cooldowns, middleware.
"""

from .checks import (
    Check,
    CheckFailure,
    CheckFailureError,
    check,
    check_any,
    cooldown,
    dm_only,
    guild_only,
    is_admin,
    is_group_chat,
    is_owner,
    is_private_message,
)
from .cog import Cog
from .context import Context
from .core import Command, Group, GroupMixin, command, group
from .cooldowns import (
    BucketType,
    Cooldown,
    CooldownMapping,
    MaxConcurrency,
    MaxConcurrencyMapping,
    MaxConcurrencyReached,
    MaxConcurrencyReachedError,
    OnCooldown,
    OnCooldownError,
    dynamic_cooldown,
)
from .middleware import (
    Middleware,
    MiddlewareManager,
    MiddlewarePriority,
    after_command,
    before_command,
    middleware,
)
from .listener import (
    CHAT_ACTION_ALIASES,
    CHAT_ACTION_EVENTS,
    Listener,
    get_action_types_for_event,
    is_chat_action_event,
    listener,
)
from .callback import CallbackHandler, callback
from .chat_actions import (
    ChatActionEvent,
    ChatActionType,
    ChatCreateEvent,
    ChatEditEvent,
    ChatPhoto,
    ChatPhotoRemoveEvent,
    ChatPhotoUpdateEvent,
    ChatTitleUpdateEvent,
    MemberJoinEvent,
    MemberRemoveEvent,
    PinMessageEvent,
    UnpinMessageEvent,
    create_chat_action_event,
)

from vkflow.commands.parsing.converters import (
    Converter,
    ConversionError,
    Greedy,
    GroupConverter,
    MentionConverter,
    ReplyMessage,
    ReplyMessageConverter,
    ReplyUser,
    UserConverter,
)
from vkflow.commands.parsing.validators import Between, Transform
from vkflow.commands.parsing.cutters import (
    DictCutter,
    EnumCutter,
    Flag,
    FlagCutter,
    Named,
    NamedArgCutter,
)

from vkflow.exceptions import CommandError, EventTimeout, EventTimeoutError
from .tasks import Loop, loop

__all__ = [
    "CHAT_ACTION_ALIASES",
    "CHAT_ACTION_EVENTS",
    "Between",
    "BucketType",
    "CallbackHandler",
    "ChatActionEvent",
    "ChatActionType",
    "ChatCreateEvent",
    "ChatEditEvent",
    "ChatPhoto",
    "ChatPhotoRemoveEvent",
    "ChatPhotoUpdateEvent",
    "ChatTitleUpdateEvent",
    "Check",
    "CheckFailure",
    "CheckFailureError",
    "Cog",
    "Command",
    "CommandError",
    "Context",
    "ConversionError",
    "Converter",
    "Cooldown",
    "CooldownMapping",
    "DictCutter",
    "EnumCutter",
    "EventTimeout",
    "EventTimeoutError",
    "Flag",
    "FlagCutter",
    "Greedy",
    "Group",
    "GroupConverter",
    "GroupMixin",
    "Listener",
    "Loop",
    "MaxConcurrency",
    "MaxConcurrencyMapping",
    "MaxConcurrencyReached",
    "MaxConcurrencyReachedError",
    "MemberJoinEvent",
    "MemberRemoveEvent",
    "MentionConverter",
    "Middleware",
    "MiddlewareManager",
    "MiddlewarePriority",
    "Named",
    "NamedArgCutter",
    "OnCooldown",
    "OnCooldownError",
    "PinMessageEvent",
    "ReplyMessage",
    "ReplyMessageConverter",
    "ReplyUser",
    "Transform",
    "UnpinMessageEvent",
    "UserConverter",
    "after_command",
    "before_command",
    "callback",
    "check",
    "check_any",
    "command",
    "cooldown",
    "create_chat_action_event",
    "dm_only",
    "dynamic_cooldown",
    "get_action_types_for_event",
    "group",
    "guild_only",
    "is_admin",
    "is_chat_action_event",
    "is_group_chat",
    "is_owner",
    "is_private_message",
    "listener",
    "loop",
    "middleware",
]
